name: Generate chat

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  generate_chat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Generate chat.svg
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: node build-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RynuRen
          author_email: pros0327@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE }}